block-beta
    columns 3
    %%newnode(("new_node"))
    space
    block:node
        element
        next
    end
    space
    space
    %%T(("'t'"))
    

    style node fill:#Ffd,stroke:#000,stroke-width:2px
